-- Contact-form storage for the public portfolio.
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 100),
  email text not null check (char_length(btrim(email)) between 1 and 254),
  message text not null check (char_length(btrim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "Anyone can submit a contact message" on public.messages;
create policy "Anyone can submit a contact message"
on public.messages
for insert
to anon
with check (
  char_length(btrim(name)) between 1 and 100
  and char_length(btrim(email)) between 1 and 254
  and char_length(btrim(message)) between 1 and 2000
);

drop policy if exists "Authenticated admin can read messages" on public.messages;
create policy "Authenticated admin can read messages"
on public.messages for select to authenticated using (true);

drop policy if exists "Authenticated admin can delete messages" on public.messages;
create policy "Authenticated admin can delete messages"
on public.messages for delete to authenticated using (true);

-- No public select, update, or delete policies are created.
